# permissions for end users to view textanalyzers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: textanalyzer-viewer-role
rules:
- apiGroups:
  - converter.operators.mytest.it
  resources:
  - textanalyzers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - converter.operators.mytest.it
  resources:
  - textanalyzers/status
  verbs:
  - get
