---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: textanalyzers.converter.operators.mytest.it
spec:
  group: converter.operators.mytest.it
  names:
    kind: TextAnalyzer
    listKind: TextAnalyzerList
    plural: textanalyzers
    singular: textanalyzer
    # Added by RR
    shortNames:
    - tan
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: TextAnalyzer is the Schema for the textanalyzers API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of TextAnalyzer
            type: object
            # Added by RR
            properties:
                text:
                  type: string
                hash:
                  type: string
                  enum: ["CRC32", "MD5", "SHA512"]
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state of TextAnalyzer
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    additionalPrinterColumns:
      - name: version
        type: string
        jsonPath: .apiVersion
        priority: 0
      - name: hash
        type: string
        jsonPath: .spec.hash
        priority: 1
      - name: text
        type: string
        jsonPath: .spec.text
        priority: 1

    served: true
    storage: true
    subresources:
      status: {}
